version: '2.0'
services:
  grafeas:
    build: .
    ports:
    - "8080:8080"
  db:
    image: postgres:11
    ports:
    - "5432:5432"
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=postgres
