version: '3.4'
services:
  grafeas:
    depends_on:
        - db
    build: .
    ports:
    - "8080:8080"
    volumes:
        - ./go/v1beta1/config.yaml:/config.yaml
    command: --config=config.yaml
  db:
    image: postgres:11
    ports:
    - "5432:5432"
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=postgres
